In [1]:
import numpy as np

In [2]:
%load_ext autoreload

In [3]:
%autoreload 2

In [29]:
from qmatrix import qmatvals, dvals, cvals
from asymptotic_r import W

In [5]:
Q = np.array([
    [-3.05, 0.05, 0, 3, 0],
    [0.000666667, -0.500666667, 0.5, 0, 0],
    [0, 15, -19, 4, 0],
    [0.015, 0, 0.05, -2.065, 2],
    [0, 0, 0, 0.01, -0.01]
])

In [6]:
Q

array([[-3.05000000e+00,  5.00000000e-02,  0.00000000e+00,
         3.00000000e+00,  0.00000000e+00],
       [ 6.66667000e-04, -5.00666667e-01,  5.00000000e-01,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  1.50000000e+01, -1.90000000e+01,
         4.00000000e+00,  0.00000000e+00],
       [ 1.50000000e-02,  0.00000000e+00,  5.00000000e-02,
        -2.06500000e+00,  2.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e-02, -1.00000000e-02]])

In [7]:
taus, lambdas, A = qmatvals(Q)

In [34]:
a_ind = np.array([0, 1], dtype='int32')
f_ind = np.array([2, 3, 4], dtype='int32')
td = 0.05
d_vals = dvals(Q, a_ind, f_ind, td, A)

In [35]:
d_vals

array([[[ 7.43781107e-05,  2.48129176e-05,  3.75930314e-02,
         -3.76914490e-02, -7.73460458e-07],
        [ 4.80177605e-04,  5.43449834e-03,  1.00012824e-01,
         -1.09387414e-01,  3.45991381e-03]],

       [[ 7.43781107e-05,  6.92750509e-04, -7.86428574e-04,
         -1.42485152e-05,  3.35484693e-05],
        [ 4.80177605e-04,  1.51725466e-01, -2.09222135e-03,
         -4.13517728e-05, -1.50072071e-01]]])

In [36]:
A[a_ind[:, None], a_ind, :].shape

(2, 2, 5)

In [11]:
C = cvals(Q, a_ind, f_ind, td, 2)
C.shape

(2, 2, 5, 3, 3)

In [12]:
C[:, :, 0, 0, 0]

array([[2.48271412e-05, 1.86203557e-03],
       [2.48271412e-05, 1.86203557e-03]])

In [13]:
C[:, :, 0, 1, 0] * 1e3

array([[0.02846883, 4.76713733],
       [0.06356183, 7.3991127 ]])

In [14]:
C[:, :, 0, 1, 1]

array([[1.37680331e-08, 1.03260247e-06],
       [1.37680331e-08, 1.03260247e-06]])

In [15]:
C[:, :, 0, 2, 0]

array([[8.53347284e-06, 7.36433849e-03],
       [9.81911821e-05, 1.78089469e-02]])

In [16]:
C[:, :, 0, 2, 1]

array([[3.36614301e-08, 3.98418421e-06],
       [5.31224568e-08, 5.44376119e-06]])

In [17]:
C[:, :, 0, 2, 2]

array([[3.81757072e-12, 2.86317801e-10],
       [3.81757072e-12, 2.86317801e-10]])

In [18]:
C[:, :, 3, 0, 0]

array([[9.59448224e-01, 2.72025557e-02],
       [3.62700639e-04, 1.02833942e-05]])

In [19]:
C[:, :, 3, 1, 0]

array([[-3.23731326e-02,  3.30315595e-02],
       [ 4.40420804e-04,  2.53208503e-05]])

In [20]:
C[:, :, 3, 1, 1]

array([[-3.62026687e-02, -1.02642862e-03],
       [-1.36857109e-05, -3.88021266e-07]])

In [21]:
C[:, :, 3, 2, 0]

array([[ 3.31652553e-03, -4.67048700e-03],
       [-6.22731612e-05,  1.24503001e-05]])

In [22]:
C[:, :, 3, 2, 1]

array([[ 2.44474907e-03, -1.21169216e-03],
       [-1.61558960e-05, -9.42316090e-07]])

In [23]:
C[:, :, 3, 2, 2]

array([[6.83014042e-04, 1.93650132e-05],
       [2.58200102e-07, 7.32056455e-09]])

---

In [24]:
# D[:, :, 0] @ \
C[:, :, 1, 1, 0]

array([[ 1.06328887e-05,  1.08484094e-02],
       [ 1.44645451e-04, -1.58470011e-02]])

In [ ]:
mMax = 2
nstates = 5
nA = 2
D = dvals(Q, a_ind, f_ind, td, A)

for m in np.arange(mMax+1):
        for n in np.arange(m):
            for i in np.arange(nstates):
                tmp = np.zeros((nA, nA))
                if n == 0:
                    for j in np.arange(nstates):
                        if i == j:
                            continue
                        for r in np.arange(m):
                            tmp += D[:, :, i] @ C[:, :, j, m-1, r] \
                                * np.math.factorial(r) \
                                / (lambdas[j] - lambdas[i]) ** (r + 1)
                            print(tmp)
                            tmp -= D[:, :, j] @ C[:, :, i, m-1, r] \
                                * np.math.factorial(r) \
                                / (lambdas[i]  - lambdas[j]) ** (r + 1)
                            print(m, n, i, j, r)

In [26]:
D.shape

(2, 2, 5)

In [27]:
d_vals[:, :, 0]

array([[9.08029061e-04, 6.41171942e-05, 0.00000000e+00],
       [9.08029061e-04, 6.41171942e-05, 0.00000000e+00],
       [9.08029061e-04, 6.41171942e-05, 0.00000000e+00]])

---

In [30]:
W(0, Q, a_ind, f_ind, td)

array([[ 3.04786210e+00, -5.20233674e-02],
       [-6.93645231e-04,  2.58571428e-01]])

---

In [ ]:
qAA = Q[np.ix_(a_ind, a_ind)]
qFF = Q[np.ix_(f_ind, f_ind)]
qAF = Q[np.ix_(a_ind, f_ind)]
qFA = Q[np.ix_(f_ind, a_ind)]

In [ ]:
eQFFt = scipy.linalg.expm(qFF*td)
nA = A.shape[0]
nQ = Q.shape[0]

In [ ]:
qAF

In [ ]:
eQFFt

In [ ]:
A[a_ind[:, None], f_ind, 0] @ eQFFt @ qFA

In [ ]:
A[:, :, 0, None]

In [ ]:
A[:, :3, 0]

In [ ]:
for ii in np.arange(nQ):
        D[:, :, ii] = specA[A, F, ii] @ eQFFt @ qFA

In [ ]:
D = np.zeros((nA, nA, nQ))

In [ ]:
a_ind[None, :].shape

In [ ]:
Q[a_ind[:, None], f_ind[None, :]]

In [ ]:
Q[a_ind[:, np.newaxis], f_ind]

In [ ]:
Q[:2, 2:]

In [ ]:
Q[:2, :]

In [ ]:
Q[a_ind, a_ind]

In [ ]:
Q[:2, :2]

In [ ]:
Q[a_ind[:, np.newaxis], a_ind]

In [ ]:
Q[np.ix_(a_ind, a_ind)]

In [ ]:
Q[np.ix_(f_ind, f_ind)]

In [ ]:
Q[2:, 2:]

In [ ]:
Q[f_ind[:, np.newaxis], f_ind]

In [ ]:
Q[f_ind[None], f_ind]

---

In [93]:
from asymptotic_r import W, detW

In [90]:
import scipy.linalg

In [88]:
W(0, Q, a_ind, f_ind, td)

array([[ 3.04786210e+00, -5.20233674e-02],
       [-6.93645231e-04,  2.58571428e-01]])

In [92]:
scipy.linalg.det(W(0, Q, a_ind, f_ind, td))

0.788053970021225

In [95]:
detW(0, Q, a_ind, f_ind, td)

0.788053970021225

In [38]:
d_vals[:, :, 2]

array([[ 0.03759303,  0.10001282],
       [-0.00078643, -0.00209222]])

In [37]:
d_vals.shape

(2, 2, 5)

In [40]:
np.math.ceil(0.3)

1

In [41]:
np.ceil(0.4)

1.0

In [42]:
np.abs(-4.5)

[autoreload of qmatrix failed: Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 245, in check
    superreload(m, reload, self.old_objects)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 368, in superreload
    module = reload(module)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/imp.py", line 315, in reload
    return importlib.reload(module)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/importlib/__init__.py", line 166, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>"

4.5